using System;
namespace GusBoy
{
    public partial class CPU
    {
        private struct extopcode
        {
            public string mnemonic;
            public Func<int> func;

            public extopcode(string name, Func<int> func)
            {
                this.mnemonic = name;
                this.func = func;
            }
        }

        private readonly extopcode[] extendedOpcodes;

        private extopcode[] GenerateExtendedOpcodes() => new extopcode[]
            {
                /* 0x00 */ new extopcode("RLC B", this.rlc_b),
                /* 0x01 */ new extopcode("RLC C", this.rlc_c),
                /* 0x02 */ new extopcode("RLC D", this.rlc_d),
                /* 0x03 */ new extopcode("RLC E", this.rlc_e),
                /* 0x04 */ new extopcode("RLC H", this.rlc_h),
                /* 0x05 */ new extopcode("RLC L", this.rlc_l),
                /* 0x06 */ new extopcode("RLC (HL)", this.rlc_phl),
                /* 0x07 */ new extopcode("RLC A", this.erlc_a),
                /* 0x08 */ new extopcode("RRC B", this.rrc_b),
                /* 0x09 */ new extopcode("RRC C", this.rrc_c),
                /* 0x0A */ new extopcode("RRC D", this.rrc_d),
                /* 0x0B */ new extopcode("RRC E", this.rrc_e),
                /* 0x0C */ new extopcode("RRC H", this.rrc_h),
                /* 0x0D */ new extopcode("RRC L", this.rrc_l),
                /* 0x0E */ new extopcode("RRC (HL)", this.rrc_phl),
                /* 0x0F */ new extopcode("RRC A", this.errc_a),

                /* 0x10 */ new extopcode("RL B", this.rl_b),
                /* 0x11 */ new extopcode("RL C", this.rl_c),
                /* 0x12 */ new extopcode("RL D", this.rl_d),
                /* 0x13 */ new extopcode("RL E", this.rl_e),
                /* 0x14 */ new extopcode("RL H", this.rl_h),
                /* 0x15 */ new extopcode("RL L", this.rl_l),
                /* 0x16 */ new extopcode("RL (HL)", this.rl_phl),
                /* 0x17 */ new extopcode("RL A", this.erl_a),
                /* 0x18 */ new extopcode("RR B", this.rr_b),
                /* 0x19 */ new extopcode("RR C", this.rr_c),
                /* 0x1A */ new extopcode("RR D", this.rr_d),
                /* 0x1B */ new extopcode("RR E", this.rr_e),
                /* 0x1C */ new extopcode("RR H", this.rr_h),
                /* 0x1D */ new extopcode("RR L", this.rr_l),
                /* 0x1E */ new extopcode("RR (HL)", this.rr_phl),
                /* 0x1F */ new extopcode("RR A", this.err_a),

                /* 0x20 */ new extopcode("SLA B", this.sla_b),
                /* 0x21 */ new extopcode("SLA C", this.sla_c),
                /* 0x22 */ new extopcode("SLA D", this.sla_d),
                /* 0x23 */ new extopcode("SLA E", this.sla_e),
                /* 0x24 */ new extopcode("SLA H", this.sla_h),
                /* 0x25 */ new extopcode("SLA L", this.sla_l),
                /* 0x26 */ new extopcode("SLA (HL)", this.sla_phl),
                /* 0x27 */ new extopcode("SLA A", this.sla_a),
                /* 0x28 */ new extopcode("SRA B", this.sra_b),
                /* 0x29 */ new extopcode("SRA C", this.sra_c),
                /* 0x2A */ new extopcode("SRA D", this.sra_d),
                /* 0x2B */ new extopcode("SRA E", this.sra_e),
                /* 0x2C */ new extopcode("SRA H", this.sra_h),
                /* 0x2D */ new extopcode("SRA L", this.sra_l),
                /* 0x2E */ new extopcode("SRA (HL)", this.sra_phl),
                /* 0x2F */ new extopcode("SRA A", this.sra_a),

                /* 0x30 */ new extopcode("SWAP B", this.swap_b),
                /* 0x31 */ new extopcode("SWAP C", this.swap_c),
                /* 0x32 */ new extopcode("SWAP D", this.swap_d),
                /* 0x33 */ new extopcode("SWAP E", this.swap_e),
                /* 0x34 */ new extopcode("SWAP H", this.swap_h),
                /* 0x35 */ new extopcode("SWAP L", this.swap_l),
                /* 0x36 */ new extopcode("SWAP (HL)", this.swap_phl),
                /* 0x37 */ new extopcode("SWAP A", this.swap_a),
                /* 0x38 */ new extopcode("SRL B", this.srl_b),
                /* 0x39 */ new extopcode("SRL C", this.srl_c),
                /* 0x3A */ new extopcode("SRL D", this.srl_d),
                /* 0x3B */ new extopcode("SRL E", this.srl_e),
                /* 0x3C */ new extopcode("SRL H", this.srl_h),
                /* 0x3D */ new extopcode("SRL L", this.srl_l),
                /* 0x3E */ new extopcode("SRL (HL)", this.srl_phl),
                /* 0x3F */ new extopcode("SRL A", this.srl_a),
                
                /* 0x40 */ new extopcode("BIT 0, B", this.bit_0_b),
                /* 0x41 */ new extopcode("BIT 0, C", this.bit_0_c),
                /* 0x42 */ new extopcode("BIT 0, D", this.bit_0_d),
                /* 0x43 */ new extopcode("BIT 0, E", this.bit_0_e),
                /* 0x44 */ new extopcode("BIT 0, H", this.bit_0_h),
                /* 0x45 */ new extopcode("BIT 0, L", this.bit_0_l),
                /* 0x46 */ new extopcode("BIT 0, (HL)", this.bit_0_phl),
                /* 0x47 */ new extopcode("BIT 0, A", this.bit_0_a),
                /* 0x48 */ new extopcode("BIT 1, B", this.bit_1_b),
                /* 0x49 */ new extopcode("BIT 1, C", this.bit_1_c),
                /* 0x4A */ new extopcode("BIT 1, D", this.bit_1_d),
                /* 0x4B */ new extopcode("BIT 1, E", this.bit_1_e),
                /* 0x4C */ new extopcode("BIT 1, H", this.bit_1_h),
                /* 0x4D */ new extopcode("BIT 1, L", this.bit_1_l),
                /* 0x4E */ new extopcode("BIT 1, (HL)", this.bit_1_phl),
                /* 0x4F */ new extopcode("BIT 1, A", this.bit_1_a),

                /* 0x50 */ new extopcode("BIT 2, B", this.bit_2_b),
                /* 0x51 */ new extopcode("BIT 2, C", this.bit_2_c),
                /* 0x52 */ new extopcode("BIT 2, D", this.bit_2_d),
                /* 0x53 */ new extopcode("BIT 2, E", this.bit_2_e),
                /* 0x54 */ new extopcode("BIT 2, H", this.bit_2_h),
                /* 0x55 */ new extopcode("BIT 2, L", this.bit_2_l),
                /* 0x56 */ new extopcode("BIT 2, (HL)", this.bit_2_phl),
                /* 0x57 */ new extopcode("BIT 2, A", this.bit_2_a),
                /* 0x58 */ new extopcode("BIT 3, B", this.bit_3_b),
                /* 0x59 */ new extopcode("BIT 3, C", this.bit_3_c),
                /* 0x5A */ new extopcode("BIT 3, D", this.bit_3_d),
                /* 0x5B */ new extopcode("BIT 3, E", this.bit_3_e),
                /* 0x5C */ new extopcode("BIT 3, H", this.bit_3_h),
                /* 0x5D */ new extopcode("BIT 3, L", this.bit_3_l),
                /* 0x5E */ new extopcode("BIT 3, (HL)", this.bit_3_phl),
                /* 0x5F */ new extopcode("BIT 3, A", this.bit_3_a),

                /* 0x60 */ new extopcode("BIT 4, B", this.bit_4_b),
                /* 0x61 */ new extopcode("BIT 4, C", this.bit_4_c),
                /* 0x62 */ new extopcode("BIT 4, D", this.bit_4_d),
                /* 0x63 */ new extopcode("BIT 4, E", this.bit_4_e),
                /* 0x64 */ new extopcode("BIT 4, H", this.bit_4_h),
                /* 0x65 */ new extopcode("BIT 4, L", this.bit_4_l),
                /* 0x66 */ new extopcode("BIT 4, (HL)", this.bit_4_phl),
                /* 0x67 */ new extopcode("BIT 4, A", this.bit_4_a),
                /* 0x68 */ new extopcode("BIT 5, B", this.bit_5_b),
                /* 0x69 */ new extopcode("BIT 5, C", this.bit_5_c),
                /* 0x6A */ new extopcode("BIT 5, D", this.bit_5_d),
                /* 0x6B */ new extopcode("BIT 5, E", this.bit_5_e),
                /* 0x6C */ new extopcode("BIT 5, H", this.bit_5_h),
                /* 0x6D */ new extopcode("BIT 5, L", this.bit_5_l),
                /* 0x6E */ new extopcode("BIT 5, (HL)", this.bit_5_phl),
                /* 0x6F */ new extopcode("BIT 5, A", this.bit_5_a),

                /* 0x70 */ new extopcode("BIT 6, B", this.bit_6_b),
                /* 0x71 */ new extopcode("BIT 6, C", this.bit_6_c),
                /* 0x72 */ new extopcode("BIT 6, D", this.bit_6_d),
                /* 0x73 */ new extopcode("BIT 6, E", this.bit_6_e),
                /* 0x74 */ new extopcode("BIT 6, H", this.bit_6_h),
                /* 0x75 */ new extopcode("BIT 6, L", this.bit_6_l),
                /* 0x76 */ new extopcode("BIT 6, (HL)", this.bit_6_phl),
                /* 0x77 */ new extopcode("BIT 6, A", this.bit_6_a),
                /* 0x78 */ new extopcode("BIT 7, B", this.bit_7_b),
                /* 0x79 */ new extopcode("BIT 7, C", this.bit_7_c),
                /* 0x7A */ new extopcode("BIT 7, D", this.bit_7_d),
                /* 0x7B */ new extopcode("BIT 7, E", this.bit_7_e),
                /* 0x7C */ new extopcode("BIT 7, H", this.bit_7_h),
                /* 0x7D */ new extopcode("BIT 7, L", this.bit_7_l),
                /* 0x7E */ new extopcode("BIT 7, (HL)", this.bit_7_phl),
                /* 0x7F */ new extopcode("BIT 7, A", this.bit_7_a),

                /* 0x80 */ new extopcode("RES 0, B", this.res_0_b),
                /* 0x81 */ new extopcode("RES 0, C", this.res_0_c),
                /* 0x82 */ new extopcode("RES 0, D", this.res_0_d),
                /* 0x83 */ new extopcode("RES 0, E", this.res_0_e),
                /* 0x84 */ new extopcode("RES 0, H", this.res_0_h),
                /* 0x85 */ new extopcode("RES 0, L", this.res_0_l),
                /* 0x86 */ new extopcode("RES 0, (HL)", this.res_0_phl),
                /* 0x87 */ new extopcode("RES 0, A", this.res_0_a),
                /* 0x88 */ new extopcode("RES 1, B", this.res_1_b),
                /* 0x89 */ new extopcode("RES 1, C", this.res_1_c),
                /* 0x8A */ new extopcode("RES 1, D", this.res_1_d),
                /* 0x8B */ new extopcode("RES 1, E", this.res_1_e),
                /* 0x8C */ new extopcode("RES 1, H", this.res_1_h),
                /* 0x8D */ new extopcode("RES 1, L", this.res_1_l),
                /* 0x8E */ new extopcode("RES 1, (HL)", this.res_1_phl),
                /* 0x8F */ new extopcode("RES 1, A", this.res_1_a),

                /* 0x90 */ new extopcode("RES 2, B", this.res_2_b),
                /* 0x91 */ new extopcode("RES 2, C", this.res_2_c),
                /* 0x92 */ new extopcode("RES 2, D", this.res_2_d),
                /* 0x93 */ new extopcode("RES 2, E", this.res_2_e),
                /* 0x94 */ new extopcode("RES 2, H", this.res_2_h),
                /* 0x95 */ new extopcode("RES 2, L", this.res_2_l),
                /* 0x96 */ new extopcode("RES 2, (HL)", this.res_2_phl),
                /* 0x97 */ new extopcode("RES 2, A", this.res_2_a),
                /* 0x98 */ new extopcode("RES 3, B", this.res_3_b),
                /* 0x99 */ new extopcode("RES 3, C", this.res_3_c),
                /* 0x9A */ new extopcode("RES 3, D", this.res_3_d),
                /* 0x9B */ new extopcode("RES 3, E", this.res_3_e),
                /* 0x9C */ new extopcode("RES 3, H", this.res_3_h),
                /* 0x9D */ new extopcode("RES 3, L", this.res_3_l),
                /* 0x9E */ new extopcode("RES 3, (HL)", this.res_3_phl),
                /* 0x9F */ new extopcode("RES 3, A", this.res_3_a),

                /* 0xA0 */ new extopcode("RES 4, B", this.res_4_b),
                /* 0xA1 */ new extopcode("RES 4, C", this.res_4_c),
                /* 0xA2 */ new extopcode("RES 4, D", this.res_4_d),
                /* 0xA3 */ new extopcode("RES 4, E", this.res_4_e),
                /* 0xA4 */ new extopcode("RES 4, H", this.res_4_h),
                /* 0xA5 */ new extopcode("RES 4, L", this.res_4_l),
                /* 0xA6 */ new extopcode("RES 4, (HL)", this.res_4_phl),
                /* 0xA7 */ new extopcode("RES 4, A", this.res_4_a),
                /* 0xA8 */ new extopcode("RES 5, B", this.res_5_b),
                /* 0xA9 */ new extopcode("RES 5, C", this.res_5_c),
                /* 0xAA */ new extopcode("RES 5, D", this.res_5_d),
                /* 0xAB */ new extopcode("RES 5, E", this.res_5_e),
                /* 0xAC */ new extopcode("RES 5, H", this.res_5_h),
                /* 0xAD */ new extopcode("RES 5, L", this.res_5_l),
                /* 0xAE */ new extopcode("RES 5, (HL)", this.res_5_phl),
                /* 0xAF */ new extopcode("RES 5, A", this.res_5_a),

                /* 0xB0 */ new extopcode("RES 6, B", this.res_6_b),
                /* 0xB1 */ new extopcode("RES 6, C", this.res_6_c),
                /* 0xB2 */ new extopcode("RES 6, D", this.res_6_d),
                /* 0xB3 */ new extopcode("RES 6, E", this.res_6_e),
                /* 0xB4 */ new extopcode("RES 6, H", this.res_6_h),
                /* 0xB5 */ new extopcode("RES 6, L", this.res_6_l),
                /* 0xB6 */ new extopcode("RES 6, (HL)", this.res_6_phl),
                /* 0xB7 */ new extopcode("RES 6, A", this.res_6_a),
                /* 0xB8 */ new extopcode("RES 7, B", this.res_7_b),
                /* 0xB9 */ new extopcode("RES 7, C", this.res_7_c),
                /* 0xBA */ new extopcode("RES 7, D", this.res_7_d),
                /* 0xBB */ new extopcode("RES 7, E", this.res_7_e),
                /* 0xBC */ new extopcode("RES 7, H", this.res_7_h),
                /* 0xBD */ new extopcode("RES 7, L", this.res_7_l),
                /* 0xBE */ new extopcode("RES 7, (HL)", this.res_7_phl),
                /* 0xBF */ new extopcode("RES 7, A", this.res_7_a),

                /* 0xC0 */ new extopcode("SET 0, B", this.set_0_b),
                /* 0xC1 */ new extopcode("SET 0, C", this.set_0_c),
                /* 0xC2 */ new extopcode("SET 0, D", this.set_0_d),
                /* 0xC3 */ new extopcode("SET 0, E", this.set_0_e),
                /* 0xC4 */ new extopcode("SET 0, H", this.set_0_h),
                /* 0xC5 */ new extopcode("SET 0, L", this.set_0_l),
                /* 0xC6 */ new extopcode("SET 0, (HL)", this.set_0_phl),
                /* 0xC7 */ new extopcode("SET 0, A", this.set_0_a),
                /* 0xC8 */ new extopcode("SET 1, B", this.set_1_b),
                /* 0xC9 */ new extopcode("SET 1, C", this.set_1_c),
                /* 0xCA */ new extopcode("SET 1, D", this.set_1_d),
                /* 0xCB */ new extopcode("SET 1, E", this.set_1_e),
                /* 0xCC */ new extopcode("SET 1, H", this.set_1_h),
                /* 0xCD */ new extopcode("SET 1, L", this.set_1_l),
                /* 0xCE */ new extopcode("SET 1, (HL)", this.set_1_phl),
                /* 0xCF */ new extopcode("SET 1, A", this.set_1_a),

                /* 0xD0 */ new extopcode("SET 2, B", this.set_2_b),
                /* 0xD1 */ new extopcode("SET 2, C", this.set_2_c),
                /* 0xD2 */ new extopcode("SET 2, D", this.set_2_d),
                /* 0xD3 */ new extopcode("SET 2, E", this.set_2_e),
                /* 0xD4 */ new extopcode("SET 2, H", this.set_2_h),
                /* 0xD5 */ new extopcode("SET 2, L", this.set_2_l),
                /* 0xD6 */ new extopcode("SET 2, (HL)", this.set_2_phl),
                /* 0xD7 */ new extopcode("SET 2, A", this.set_2_a),
                /* 0xD8 */ new extopcode("SET 3, B", this.set_3_b),
                /* 0xD9 */ new extopcode("SET 3, C", this.set_3_c),
                /* 0xDA */ new extopcode("SET 3, D", this.set_3_d),
                /* 0xDB */ new extopcode("SET 3, E", this.set_3_e),
                /* 0xDC */ new extopcode("SET 3, H", this.set_3_h),
                /* 0xDD */ new extopcode("SET 3, L", this.set_3_l),
                /* 0xDE */ new extopcode("SET 3, (HL)", this.set_3_phl),
                /* 0xDF */ new extopcode("SET 3, A", this.set_3_a),

                /* 0xE0 */ new extopcode("SET 4, B", this.set_4_b),
                /* 0xE1 */ new extopcode("SET 4, C", this.set_4_c),
                /* 0xE2 */ new extopcode("SET 4, D", this.set_4_d),
                /* 0xE3 */ new extopcode("SET 4, E", this.set_4_e),
                /* 0xE4 */ new extopcode("SET 4, H", this.set_4_h),
                /* 0xE5 */ new extopcode("SET 4, L", this.set_4_l),
                /* 0xE6 */ new extopcode("SET 4, (HL)", this.set_4_phl),
                /* 0xE7 */ new extopcode("SET 4, A", this.set_4_a),
                /* 0xE8 */ new extopcode("SET 5, B", this.set_5_b),
                /* 0xE9 */ new extopcode("SET 5, C", this.set_5_c),
                /* 0xEA */ new extopcode("SET 5, D", this.set_5_d),
                /* 0xEB */ new extopcode("SET 5, E", this.set_5_e),
                /* 0xEC */ new extopcode("SET 5, H", this.set_5_h),
                /* 0xED */ new extopcode("SET 5, L", this.set_5_l),
                /* 0xEE */ new extopcode("SET 5, (HL)", this.set_5_phl),
                /* 0xEF */ new extopcode("SET 5, A", this.set_5_a),

                /* 0xF0 */ new extopcode("SET 6, B", this.set_6_b),
                /* 0xF1 */ new extopcode("SET 6, C", this.set_6_c),
                /* 0xF2 */ new extopcode("SET 6, D", this.set_6_d),
                /* 0xF3 */ new extopcode("SET 6, E", this.set_6_e),
                /* 0xF4 */ new extopcode("SET 6, H", this.set_6_h),
                /* 0xF5 */ new extopcode("SET 6, L", this.set_6_l),
                /* 0xF6 */ new extopcode("SET 6, (HL)", this.set_6_phl),
                /* 0xF7 */ new extopcode("SET 6, A", this.set_6_a),
                /* 0xF8 */ new extopcode("SET 7, B", this.set_7_b),
                /* 0xF9 */ new extopcode("SET 7, C", this.set_7_c),
                /* 0xFA */ new extopcode("SET 7, D", this.set_7_d),
                /* 0xFB */ new extopcode("SET 7, E", this.set_7_e),
                /* 0xFC */ new extopcode("SET 7, H", this.set_7_h),
                /* 0xFD */ new extopcode("SET 7, L", this.set_7_l),
                /* 0xFE */ new extopcode("SET 7, (HL)", this.set_7_phl),
                /* 0xFF */ new extopcode("SET 7, A", this.set_7_a),
            };
    }
}