using System;
namespace GusBoy
{
    public partial class CPU
    {
        struct extopcode
        {
            public string mnemonic;
            public Func<int> func;

            public extopcode(string name, Func<int> func)
            {
                this.mnemonic = name;
                this.func = func;
            }
        }

        private extopcode[] extendedOpcodes;

        private extopcode[] GenerateExtendedOpcodes()
        {
            return new extopcode[]
            {
                /* 0x00 */ new extopcode("RLC B", rlc_b),
                /* 0x01 */ new extopcode("RLC C", rlc_c),
                /* 0x02 */ new extopcode("RLC D", rlc_d),
                /* 0x03 */ new extopcode("RLC E", rlc_e),
                /* 0x04 */ new extopcode("RLC H", rlc_h),
                /* 0x05 */ new extopcode("RLC L", rlc_l),
                /* 0x06 */ new extopcode("RLC (HL)", rlc_phl),
                /* 0x07 */ new extopcode("RLC A", erlc_a),
                /* 0x08 */ new extopcode("RRC B", rrc_b),
                /* 0x09 */ new extopcode("RRC C", rrc_c),
                /* 0x0A */ new extopcode("RRC D", rrc_d),
                /* 0x0B */ new extopcode("RRC E", rrc_e),
                /* 0x0C */ new extopcode("RRC H", rrc_h),
                /* 0x0D */ new extopcode("RRC L", rrc_l),
                /* 0x0E */ new extopcode("RRC (HL)", rrc_phl),
                /* 0x0F */ new extopcode("RRC A", errc_a),

                /* 0x10 */ new extopcode("RL B", rl_b),
                /* 0x11 */ new extopcode("RL C", rl_c),
                /* 0x12 */ new extopcode("RL D", rl_d),
                /* 0x13 */ new extopcode("RL E", rl_e),
                /* 0x14 */ new extopcode("RL H", rl_h),
                /* 0x15 */ new extopcode("RL L", rl_l),
                /* 0x16 */ new extopcode("RL (HL)", rl_phl),
                /* 0x17 */ new extopcode("RL A", erl_a),
                /* 0x18 */ new extopcode("RR B", rr_b),
                /* 0x19 */ new extopcode("RR C", rr_c),
                /* 0x1A */ new extopcode("RR D", rr_d),
                /* 0x1B */ new extopcode("RR E", rr_e),
                /* 0x1C */ new extopcode("RR H", rr_h),
                /* 0x1D */ new extopcode("RR L", rr_l),
                /* 0x1E */ new extopcode("RR (HL)", rr_phl),
                /* 0x1F */ new extopcode("RR A", err_a),

                /* 0x20 */ new extopcode("SLA B", sla_b),
                /* 0x21 */ new extopcode("SLA C", sla_c),
                /* 0x22 */ new extopcode("SLA D", sla_d),
                /* 0x23 */ new extopcode("SLA E", sla_e),
                /* 0x24 */ new extopcode("SLA H", sla_h),
                /* 0x25 */ new extopcode("SLA L", sla_l),
                /* 0x26 */ new extopcode("SLA (HL)", sla_phl),
                /* 0x27 */ new extopcode("SLA A", sla_a),
                /* 0x28 */ new extopcode("SRA B", sra_b),
                /* 0x29 */ new extopcode("SRA C", sra_c),
                /* 0x2A */ new extopcode("SRA D", sra_d),
                /* 0x2B */ new extopcode("SRA E", sra_e),
                /* 0x2C */ new extopcode("SRA H", sra_h),
                /* 0x2D */ new extopcode("SRA L", sra_l),
                /* 0x2E */ new extopcode("SRA (HL)", sra_phl),
                /* 0x2F */ new extopcode("SRA A", sra_a),

                /* 0x30 */ new extopcode("SWAP B", swap_b),
                /* 0x31 */ new extopcode("SWAP C", swap_c),
                /* 0x32 */ new extopcode("SWAP D", swap_d),
                /* 0x33 */ new extopcode("SWAP E", swap_e),
                /* 0x34 */ new extopcode("SWAP H", swap_h),
                /* 0x35 */ new extopcode("SWAP L", swap_l),
                /* 0x36 */ new extopcode("SWAP (HL)", swap_phl),
                /* 0x37 */ new extopcode("SWAP A", swap_a),
                /* 0x38 */ new extopcode("SRL B", srl_b),
                /* 0x39 */ new extopcode("SRL C", srl_c),
                /* 0x3A */ new extopcode("SRL D", srl_d),
                /* 0x3B */ new extopcode("SRL E", srl_e),
                /* 0x3C */ new extopcode("SRL H", srl_h),
                /* 0x3D */ new extopcode("SRL L", srl_l),
                /* 0x3E */ new extopcode("SRL (HL)", srl_phl),
                /* 0x3F */ new extopcode("SRL A", srl_a),
                
                /* 0x40 */ new extopcode("BIT 0, B", bit_0_b),
                /* 0x41 */ new extopcode("BIT 0, C", bit_0_c),
                /* 0x42 */ new extopcode("BIT 0, D", bit_0_d),
                /* 0x43 */ new extopcode("BIT 0, E", bit_0_e),
                /* 0x44 */ new extopcode("BIT 0, H", bit_0_h),
                /* 0x45 */ new extopcode("BIT 0, L", bit_0_l),
                /* 0x46 */ new extopcode("BIT 0, (HL)", bit_0_phl),
                /* 0x47 */ new extopcode("BIT 0, A", bit_0_a),
                /* 0x48 */ new extopcode("BIT 1, B", bit_1_b),
                /* 0x49 */ new extopcode("BIT 1, C", bit_1_c),
                /* 0x4A */ new extopcode("BIT 1, D", bit_1_d),
                /* 0x4B */ new extopcode("BIT 1, E", bit_1_e),
                /* 0x4C */ new extopcode("BIT 1, H", bit_1_h),
                /* 0x4D */ new extopcode("BIT 1, L", bit_1_l),
                /* 0x4E */ new extopcode("BIT 1, (HL)", bit_1_phl),
                /* 0x4F */ new extopcode("BIT 1, A", bit_1_a),

                /* 0x50 */ new extopcode("BIT 2, B", bit_2_b),
                /* 0x51 */ new extopcode("BIT 2, C", bit_2_c),
                /* 0x52 */ new extopcode("BIT 2, D", bit_2_d),
                /* 0x53 */ new extopcode("BIT 2, E", bit_2_e),
                /* 0x54 */ new extopcode("BIT 2, H", bit_2_h),
                /* 0x55 */ new extopcode("BIT 2, L", bit_2_l),
                /* 0x56 */ new extopcode("BIT 2, (HL)", bit_2_phl),
                /* 0x57 */ new extopcode("BIT 2, A", bit_2_a),
                /* 0x58 */ new extopcode("BIT 3, B", bit_3_b),
                /* 0x59 */ new extopcode("BIT 3, C", bit_3_c),
                /* 0x5A */ new extopcode("BIT 3, D", bit_3_d),
                /* 0x5B */ new extopcode("BIT 3, E", bit_3_e),
                /* 0x5C */ new extopcode("BIT 3, H", bit_3_h),
                /* 0x5D */ new extopcode("BIT 3, L", bit_3_l),
                /* 0x5E */ new extopcode("BIT 3, (HL)", bit_3_phl),
                /* 0x5F */ new extopcode("BIT 3, A", bit_3_a),

                /* 0x60 */ new extopcode("BIT 4, B", bit_4_b),
                /* 0x61 */ new extopcode("BIT 4, C", bit_4_c),
                /* 0x62 */ new extopcode("BIT 4, D", bit_4_d),
                /* 0x63 */ new extopcode("BIT 4, E", bit_4_e),
                /* 0x64 */ new extopcode("BIT 4, H", bit_4_h),
                /* 0x65 */ new extopcode("BIT 4, L", bit_4_l),
                /* 0x66 */ new extopcode("BIT 4, (HL)", bit_4_phl),
                /* 0x67 */ new extopcode("BIT 4, A", bit_4_a),
                /* 0x68 */ new extopcode("BIT 5, B", bit_5_b),
                /* 0x69 */ new extopcode("BIT 5, C", bit_5_c),
                /* 0x6A */ new extopcode("BIT 5, D", bit_5_d),
                /* 0x6B */ new extopcode("BIT 5, E", bit_5_e),
                /* 0x6C */ new extopcode("BIT 5, H", bit_5_h),
                /* 0x6D */ new extopcode("BIT 5, L", bit_5_l),
                /* 0x6E */ new extopcode("BIT 5, (HL)", bit_5_phl),
                /* 0x6F */ new extopcode("BIT 5, A", bit_5_a),

                /* 0x70 */ new extopcode("BIT 6, B", bit_6_b),
                /* 0x71 */ new extopcode("BIT 6, C", bit_6_c),
                /* 0x72 */ new extopcode("BIT 6, D", bit_6_d),
                /* 0x73 */ new extopcode("BIT 6, E", bit_6_e),
                /* 0x74 */ new extopcode("BIT 6, H", bit_6_h),
                /* 0x75 */ new extopcode("BIT 6, L", bit_6_l),
                /* 0x76 */ new extopcode("BIT 6, (HL)", bit_6_phl),
                /* 0x77 */ new extopcode("BIT 6, A", bit_6_a),
                /* 0x78 */ new extopcode("BIT 7, B", bit_7_b),
                /* 0x79 */ new extopcode("BIT 7, C", bit_7_c),
                /* 0x7A */ new extopcode("BIT 7, D", bit_7_d),
                /* 0x7B */ new extopcode("BIT 7, E", bit_7_e),
                /* 0x7C */ new extopcode("BIT 7, H", bit_7_h),
                /* 0x7D */ new extopcode("BIT 7, L", bit_7_l),
                /* 0x7E */ new extopcode("BIT 7, (HL)", bit_7_phl),
                /* 0x7F */ new extopcode("BIT 7, A", bit_7_a),

                /* 0x80 */ new extopcode("RES 0, B", res_0_b),
                /* 0x81 */ new extopcode("RES 0, C", res_0_c),
                /* 0x82 */ new extopcode("RES 0, D", res_0_d),
                /* 0x83 */ new extopcode("RES 0, E", res_0_e),
                /* 0x84 */ new extopcode("RES 0, H", res_0_h),
                /* 0x85 */ new extopcode("RES 0, L", res_0_l),
                /* 0x86 */ new extopcode("RES 0, (HL)", res_0_phl),
                /* 0x87 */ new extopcode("RES 0, A", res_0_a),
                /* 0x88 */ new extopcode("RES 1, B", res_1_b),
                /* 0x89 */ new extopcode("RES 1, C", res_1_c),
                /* 0x8A */ new extopcode("RES 1, D", res_1_d),
                /* 0x8B */ new extopcode("RES 1, E", res_1_e),
                /* 0x8C */ new extopcode("RES 1, H", res_1_h),
                /* 0x8D */ new extopcode("RES 1, L", res_1_l),
                /* 0x8E */ new extopcode("RES 1, (HL)", res_1_phl),
                /* 0x8F */ new extopcode("RES 1, A", res_1_a),

                /* 0x90 */ new extopcode("RES 2, B", res_2_b),
                /* 0x91 */ new extopcode("RES 2, C", res_2_c),
                /* 0x92 */ new extopcode("RES 2, D", res_2_d),
                /* 0x93 */ new extopcode("RES 2, E", res_2_e),
                /* 0x94 */ new extopcode("RES 2, H", res_2_h),
                /* 0x95 */ new extopcode("RES 2, L", res_2_l),
                /* 0x96 */ new extopcode("RES 2, (HL)", res_2_phl),
                /* 0x97 */ new extopcode("RES 2, A", res_2_a),
                /* 0x98 */ new extopcode("RES 3, B", res_3_b),
                /* 0x99 */ new extopcode("RES 3, C", res_3_c),
                /* 0x9A */ new extopcode("RES 3, D", res_3_d),
                /* 0x9B */ new extopcode("RES 3, E", res_3_e),
                /* 0x9C */ new extopcode("RES 3, H", res_3_h),
                /* 0x9D */ new extopcode("RES 3, L", res_3_l),
                /* 0x9E */ new extopcode("RES 3, (HL)", res_3_phl),
                /* 0x9F */ new extopcode("RES 3, A", res_3_a),

                /* 0xA0 */ new extopcode("RES 4, B", res_4_b),
                /* 0xA1 */ new extopcode("RES 4, C", res_4_c),
                /* 0xA2 */ new extopcode("RES 4, D", res_4_d),
                /* 0xA3 */ new extopcode("RES 4, E", res_4_e),
                /* 0xA4 */ new extopcode("RES 4, H", res_4_h),
                /* 0xA5 */ new extopcode("RES 4, L", res_4_l),
                /* 0xA6 */ new extopcode("RES 4, (HL)", res_4_phl),
                /* 0xA7 */ new extopcode("RES 4, A", res_4_a),
                /* 0xA8 */ new extopcode("RES 5, B", res_5_b),
                /* 0xA9 */ new extopcode("RES 5, C", res_5_c),
                /* 0xAA */ new extopcode("RES 5, D", res_5_d),
                /* 0xAB */ new extopcode("RES 5, E", res_5_e),
                /* 0xAC */ new extopcode("RES 5, H", res_5_h),
                /* 0xAD */ new extopcode("RES 5, L", res_5_l),
                /* 0xAE */ new extopcode("RES 5, (HL)", res_5_phl),
                /* 0xAF */ new extopcode("RES 5, A", res_5_a),

                /* 0xB0 */ new extopcode("RES 6, B", res_6_b),
                /* 0xB1 */ new extopcode("RES 6, C", res_6_c),
                /* 0xB2 */ new extopcode("RES 6, D", res_6_d),
                /* 0xB3 */ new extopcode("RES 6, E", res_6_e),
                /* 0xB4 */ new extopcode("RES 6, H", res_6_h),
                /* 0xB5 */ new extopcode("RES 6, L", res_6_l),
                /* 0xB6 */ new extopcode("RES 6, (HL)", res_6_phl),
                /* 0xB7 */ new extopcode("RES 6, A", res_6_a),
                /* 0xB8 */ new extopcode("RES 7, B", res_7_b),
                /* 0xB9 */ new extopcode("RES 7, C", res_7_c),
                /* 0xBA */ new extopcode("RES 7, D", res_7_d),
                /* 0xBB */ new extopcode("RES 7, E", res_7_e),
                /* 0xBC */ new extopcode("RES 7, H", res_7_h),
                /* 0xBD */ new extopcode("RES 7, L", res_7_l),
                /* 0xBE */ new extopcode("RES 7, (HL)", res_7_phl),
                /* 0xBF */ new extopcode("RES 7, A", res_7_a),

                /* 0xC0 */ new extopcode("SET 0, B", set_0_b),
                /* 0xC1 */ new extopcode("SET 0, C", set_0_c),
                /* 0xC2 */ new extopcode("SET 0, D", set_0_d),
                /* 0xC3 */ new extopcode("SET 0, E", set_0_e),
                /* 0xC4 */ new extopcode("SET 0, H", set_0_h),
                /* 0xC5 */ new extopcode("SET 0, L", set_0_l),
                /* 0xC6 */ new extopcode("SET 0, (HL)", set_0_phl),
                /* 0xC7 */ new extopcode("SET 0, A", set_0_a),
                /* 0xC8 */ new extopcode("SET 1, B", set_1_b),
                /* 0xC9 */ new extopcode("SET 1, C", set_1_c),
                /* 0xCA */ new extopcode("SET 1, D", set_1_d),
                /* 0xCB */ new extopcode("SET 1, E", set_1_e),
                /* 0xCC */ new extopcode("SET 1, H", set_1_h),
                /* 0xCD */ new extopcode("SET 1, L", set_1_l),
                /* 0xCE */ new extopcode("SET 1, (HL)", set_1_phl),
                /* 0xCF */ new extopcode("SET 1, A", set_1_a),

                /* 0xD0 */ new extopcode("SET 2, B", set_2_b),
                /* 0xD1 */ new extopcode("SET 2, C", set_2_c),
                /* 0xD2 */ new extopcode("SET 2, D", set_2_d),
                /* 0xD3 */ new extopcode("SET 2, E", set_2_e),
                /* 0xD4 */ new extopcode("SET 2, H", set_2_h),
                /* 0xD5 */ new extopcode("SET 2, L", set_2_l),
                /* 0xD6 */ new extopcode("SET 2, (HL)", set_2_phl),
                /* 0xD7 */ new extopcode("SET 2, A", set_2_a),
                /* 0xD8 */ new extopcode("SET 3, B", set_3_b),
                /* 0xD9 */ new extopcode("SET 3, C", set_3_c),
                /* 0xDA */ new extopcode("SET 3, D", set_3_d),
                /* 0xDB */ new extopcode("SET 3, E", set_3_e),
                /* 0xDC */ new extopcode("SET 3, H", set_3_h),
                /* 0xDD */ new extopcode("SET 3, L", set_3_l),
                /* 0xDE */ new extopcode("SET 3, (HL)", set_3_phl),
                /* 0xDF */ new extopcode("SET 3, A", set_3_a),

                /* 0xE0 */ new extopcode("SET 4, B", set_4_b),
                /* 0xE1 */ new extopcode("SET 4, C", set_4_c),
                /* 0xE2 */ new extopcode("SET 4, D", set_4_d),
                /* 0xE3 */ new extopcode("SET 4, E", set_4_e),
                /* 0xE4 */ new extopcode("SET 4, H", set_4_h),
                /* 0xE5 */ new extopcode("SET 4, L", set_4_l),
                /* 0xE6 */ new extopcode("SET 4, (HL)", set_4_phl),
                /* 0xE7 */ new extopcode("SET 4, A", set_4_a),
                /* 0xE8 */ new extopcode("SET 5, B", set_5_b),
                /* 0xE9 */ new extopcode("SET 5, C", set_5_c),
                /* 0xEA */ new extopcode("SET 5, D", set_5_d),
                /* 0xEB */ new extopcode("SET 5, E", set_5_e),
                /* 0xEC */ new extopcode("SET 5, H", set_5_h),
                /* 0xED */ new extopcode("SET 5, L", set_5_l),
                /* 0xEE */ new extopcode("SET 5, (HL)", set_5_phl),
                /* 0xEF */ new extopcode("SET 5, A", set_5_a),

                /* 0xF0 */ new extopcode("SET 6, B", set_6_b),
                /* 0xF1 */ new extopcode("SET 6, C", set_6_c),
                /* 0xF2 */ new extopcode("SET 6, D", set_6_d),
                /* 0xF3 */ new extopcode("SET 6, E", set_6_e),
                /* 0xF4 */ new extopcode("SET 6, H", set_6_h),
                /* 0xF5 */ new extopcode("SET 6, L", set_6_l),
                /* 0xF6 */ new extopcode("SET 6, (HL)", set_6_phl),
                /* 0xF7 */ new extopcode("SET 6, A", set_6_a),
                /* 0xF8 */ new extopcode("SET 7, B", set_7_b),
                /* 0xF9 */ new extopcode("SET 7, C", set_7_c),
                /* 0xFA */ new extopcode("SET 7, D", set_7_d),
                /* 0xFB */ new extopcode("SET 7, E", set_7_e),
                /* 0xFC */ new extopcode("SET 7, H", set_7_h),
                /* 0xFD */ new extopcode("SET 7, L", set_7_l),
                /* 0xFE */ new extopcode("SET 7, (HL)", set_7_phl),
                /* 0xFF */ new extopcode("SET 7, A", set_7_a),
            };
        }
    }
}