namespace Gusboy
{
    using System;

    /// <summary>
    /// Definitions for two-byte opcodes.
    /// </summary>
    public partial class CPU
    {
        private readonly ExtOpcode[] extendedOpcodes;

        private ExtOpcode[] GenerateExtendedOpcodes() => new ExtOpcode[]
            {
                /* 0x00 */ new ExtOpcode("RLC B", this.rlc_b),
                /* 0x01 */ new ExtOpcode("RLC C", this.rlc_c),
                /* 0x02 */ new ExtOpcode("RLC D", this.rlc_d),
                /* 0x03 */ new ExtOpcode("RLC E", this.rlc_e),
                /* 0x04 */ new ExtOpcode("RLC H", this.rlc_h),
                /* 0x05 */ new ExtOpcode("RLC L", this.rlc_l),
                /* 0x06 */ new ExtOpcode("RLC (HL)", this.rlc_phl),
                /* 0x07 */ new ExtOpcode("RLC A", this.erlc_a),
                /* 0x08 */ new ExtOpcode("RRC B", this.rrc_b),
                /* 0x09 */ new ExtOpcode("RRC C", this.rrc_c),
                /* 0x0A */ new ExtOpcode("RRC D", this.rrc_d),
                /* 0x0B */ new ExtOpcode("RRC E", this.rrc_e),
                /* 0x0C */ new ExtOpcode("RRC H", this.rrc_h),
                /* 0x0D */ new ExtOpcode("RRC L", this.rrc_l),
                /* 0x0E */ new ExtOpcode("RRC (HL)", this.rrc_phl),
                /* 0x0F */ new ExtOpcode("RRC A", this.errc_a),

                /* 0x10 */ new ExtOpcode("RL B", this.rl_b),
                /* 0x11 */ new ExtOpcode("RL C", this.rl_c),
                /* 0x12 */ new ExtOpcode("RL D", this.rl_d),
                /* 0x13 */ new ExtOpcode("RL E", this.rl_e),
                /* 0x14 */ new ExtOpcode("RL H", this.rl_h),
                /* 0x15 */ new ExtOpcode("RL L", this.rl_l),
                /* 0x16 */ new ExtOpcode("RL (HL)", this.rl_phl),
                /* 0x17 */ new ExtOpcode("RL A", this.erl_a),
                /* 0x18 */ new ExtOpcode("RR B", this.rr_b),
                /* 0x19 */ new ExtOpcode("RR C", this.rr_c),
                /* 0x1A */ new ExtOpcode("RR D", this.rr_d),
                /* 0x1B */ new ExtOpcode("RR E", this.rr_e),
                /* 0x1C */ new ExtOpcode("RR H", this.rr_h),
                /* 0x1D */ new ExtOpcode("RR L", this.rr_l),
                /* 0x1E */ new ExtOpcode("RR (HL)", this.rr_phl),
                /* 0x1F */ new ExtOpcode("RR A", this.err_a),

                /* 0x20 */ new ExtOpcode("SLA B", this.sla_b),
                /* 0x21 */ new ExtOpcode("SLA C", this.sla_c),
                /* 0x22 */ new ExtOpcode("SLA D", this.sla_d),
                /* 0x23 */ new ExtOpcode("SLA E", this.sla_e),
                /* 0x24 */ new ExtOpcode("SLA H", this.sla_h),
                /* 0x25 */ new ExtOpcode("SLA L", this.sla_l),
                /* 0x26 */ new ExtOpcode("SLA (HL)", this.sla_phl),
                /* 0x27 */ new ExtOpcode("SLA A", this.sla_a),
                /* 0x28 */ new ExtOpcode("SRA B", this.sra_b),
                /* 0x29 */ new ExtOpcode("SRA C", this.sra_c),
                /* 0x2A */ new ExtOpcode("SRA D", this.sra_d),
                /* 0x2B */ new ExtOpcode("SRA E", this.sra_e),
                /* 0x2C */ new ExtOpcode("SRA H", this.sra_h),
                /* 0x2D */ new ExtOpcode("SRA L", this.sra_l),
                /* 0x2E */ new ExtOpcode("SRA (HL)", this.sra_phl),
                /* 0x2F */ new ExtOpcode("SRA A", this.sra_a),

                /* 0x30 */ new ExtOpcode("SWAP B", this.swap_b),
                /* 0x31 */ new ExtOpcode("SWAP C", this.swap_c),
                /* 0x32 */ new ExtOpcode("SWAP D", this.swap_d),
                /* 0x33 */ new ExtOpcode("SWAP E", this.swap_e),
                /* 0x34 */ new ExtOpcode("SWAP H", this.swap_h),
                /* 0x35 */ new ExtOpcode("SWAP L", this.swap_l),
                /* 0x36 */ new ExtOpcode("SWAP (HL)", this.swap_phl),
                /* 0x37 */ new ExtOpcode("SWAP A", this.swap_a),
                /* 0x38 */ new ExtOpcode("SRL B", this.srl_b),
                /* 0x39 */ new ExtOpcode("SRL C", this.srl_c),
                /* 0x3A */ new ExtOpcode("SRL D", this.srl_d),
                /* 0x3B */ new ExtOpcode("SRL E", this.srl_e),
                /* 0x3C */ new ExtOpcode("SRL H", this.srl_h),
                /* 0x3D */ new ExtOpcode("SRL L", this.srl_l),
                /* 0x3E */ new ExtOpcode("SRL (HL)", this.srl_phl),
                /* 0x3F */ new ExtOpcode("SRL A", this.srl_a),

                /* 0x40 */ new ExtOpcode("BIT 0, B", this.bit_0_b),
                /* 0x41 */ new ExtOpcode("BIT 0, C", this.bit_0_c),
                /* 0x42 */ new ExtOpcode("BIT 0, D", this.bit_0_d),
                /* 0x43 */ new ExtOpcode("BIT 0, E", this.bit_0_e),
                /* 0x44 */ new ExtOpcode("BIT 0, H", this.bit_0_h),
                /* 0x45 */ new ExtOpcode("BIT 0, L", this.bit_0_l),
                /* 0x46 */ new ExtOpcode("BIT 0, (HL)", this.bit_0_phl),
                /* 0x47 */ new ExtOpcode("BIT 0, A", this.bit_0_a),
                /* 0x48 */ new ExtOpcode("BIT 1, B", this.bit_1_b),
                /* 0x49 */ new ExtOpcode("BIT 1, C", this.bit_1_c),
                /* 0x4A */ new ExtOpcode("BIT 1, D", this.bit_1_d),
                /* 0x4B */ new ExtOpcode("BIT 1, E", this.bit_1_e),
                /* 0x4C */ new ExtOpcode("BIT 1, H", this.bit_1_h),
                /* 0x4D */ new ExtOpcode("BIT 1, L", this.bit_1_l),
                /* 0x4E */ new ExtOpcode("BIT 1, (HL)", this.bit_1_phl),
                /* 0x4F */ new ExtOpcode("BIT 1, A", this.bit_1_a),

                /* 0x50 */ new ExtOpcode("BIT 2, B", this.bit_2_b),
                /* 0x51 */ new ExtOpcode("BIT 2, C", this.bit_2_c),
                /* 0x52 */ new ExtOpcode("BIT 2, D", this.bit_2_d),
                /* 0x53 */ new ExtOpcode("BIT 2, E", this.bit_2_e),
                /* 0x54 */ new ExtOpcode("BIT 2, H", this.bit_2_h),
                /* 0x55 */ new ExtOpcode("BIT 2, L", this.bit_2_l),
                /* 0x56 */ new ExtOpcode("BIT 2, (HL)", this.bit_2_phl),
                /* 0x57 */ new ExtOpcode("BIT 2, A", this.bit_2_a),
                /* 0x58 */ new ExtOpcode("BIT 3, B", this.bit_3_b),
                /* 0x59 */ new ExtOpcode("BIT 3, C", this.bit_3_c),
                /* 0x5A */ new ExtOpcode("BIT 3, D", this.bit_3_d),
                /* 0x5B */ new ExtOpcode("BIT 3, E", this.bit_3_e),
                /* 0x5C */ new ExtOpcode("BIT 3, H", this.bit_3_h),
                /* 0x5D */ new ExtOpcode("BIT 3, L", this.bit_3_l),
                /* 0x5E */ new ExtOpcode("BIT 3, (HL)", this.bit_3_phl),
                /* 0x5F */ new ExtOpcode("BIT 3, A", this.bit_3_a),

                /* 0x60 */ new ExtOpcode("BIT 4, B", this.bit_4_b),
                /* 0x61 */ new ExtOpcode("BIT 4, C", this.bit_4_c),
                /* 0x62 */ new ExtOpcode("BIT 4, D", this.bit_4_d),
                /* 0x63 */ new ExtOpcode("BIT 4, E", this.bit_4_e),
                /* 0x64 */ new ExtOpcode("BIT 4, H", this.bit_4_h),
                /* 0x65 */ new ExtOpcode("BIT 4, L", this.bit_4_l),
                /* 0x66 */ new ExtOpcode("BIT 4, (HL)", this.bit_4_phl),
                /* 0x67 */ new ExtOpcode("BIT 4, A", this.bit_4_a),
                /* 0x68 */ new ExtOpcode("BIT 5, B", this.bit_5_b),
                /* 0x69 */ new ExtOpcode("BIT 5, C", this.bit_5_c),
                /* 0x6A */ new ExtOpcode("BIT 5, D", this.bit_5_d),
                /* 0x6B */ new ExtOpcode("BIT 5, E", this.bit_5_e),
                /* 0x6C */ new ExtOpcode("BIT 5, H", this.bit_5_h),
                /* 0x6D */ new ExtOpcode("BIT 5, L", this.bit_5_l),
                /* 0x6E */ new ExtOpcode("BIT 5, (HL)", this.bit_5_phl),
                /* 0x6F */ new ExtOpcode("BIT 5, A", this.bit_5_a),

                /* 0x70 */ new ExtOpcode("BIT 6, B", this.bit_6_b),
                /* 0x71 */ new ExtOpcode("BIT 6, C", this.bit_6_c),
                /* 0x72 */ new ExtOpcode("BIT 6, D", this.bit_6_d),
                /* 0x73 */ new ExtOpcode("BIT 6, E", this.bit_6_e),
                /* 0x74 */ new ExtOpcode("BIT 6, H", this.bit_6_h),
                /* 0x75 */ new ExtOpcode("BIT 6, L", this.bit_6_l),
                /* 0x76 */ new ExtOpcode("BIT 6, (HL)", this.bit_6_phl),
                /* 0x77 */ new ExtOpcode("BIT 6, A", this.bit_6_a),
                /* 0x78 */ new ExtOpcode("BIT 7, B", this.bit_7_b),
                /* 0x79 */ new ExtOpcode("BIT 7, C", this.bit_7_c),
                /* 0x7A */ new ExtOpcode("BIT 7, D", this.bit_7_d),
                /* 0x7B */ new ExtOpcode("BIT 7, E", this.bit_7_e),
                /* 0x7C */ new ExtOpcode("BIT 7, H", this.bit_7_h),
                /* 0x7D */ new ExtOpcode("BIT 7, L", this.bit_7_l),
                /* 0x7E */ new ExtOpcode("BIT 7, (HL)", this.bit_7_phl),
                /* 0x7F */ new ExtOpcode("BIT 7, A", this.bit_7_a),

                /* 0x80 */ new ExtOpcode("RES 0, B", this.res_0_b),
                /* 0x81 */ new ExtOpcode("RES 0, C", this.res_0_c),
                /* 0x82 */ new ExtOpcode("RES 0, D", this.res_0_d),
                /* 0x83 */ new ExtOpcode("RES 0, E", this.res_0_e),
                /* 0x84 */ new ExtOpcode("RES 0, H", this.res_0_h),
                /* 0x85 */ new ExtOpcode("RES 0, L", this.res_0_l),
                /* 0x86 */ new ExtOpcode("RES 0, (HL)", this.res_0_phl),
                /* 0x87 */ new ExtOpcode("RES 0, A", this.res_0_a),
                /* 0x88 */ new ExtOpcode("RES 1, B", this.res_1_b),
                /* 0x89 */ new ExtOpcode("RES 1, C", this.res_1_c),
                /* 0x8A */ new ExtOpcode("RES 1, D", this.res_1_d),
                /* 0x8B */ new ExtOpcode("RES 1, E", this.res_1_e),
                /* 0x8C */ new ExtOpcode("RES 1, H", this.res_1_h),
                /* 0x8D */ new ExtOpcode("RES 1, L", this.res_1_l),
                /* 0x8E */ new ExtOpcode("RES 1, (HL)", this.res_1_phl),
                /* 0x8F */ new ExtOpcode("RES 1, A", this.res_1_a),

                /* 0x90 */ new ExtOpcode("RES 2, B", this.res_2_b),
                /* 0x91 */ new ExtOpcode("RES 2, C", this.res_2_c),
                /* 0x92 */ new ExtOpcode("RES 2, D", this.res_2_d),
                /* 0x93 */ new ExtOpcode("RES 2, E", this.res_2_e),
                /* 0x94 */ new ExtOpcode("RES 2, H", this.res_2_h),
                /* 0x95 */ new ExtOpcode("RES 2, L", this.res_2_l),
                /* 0x96 */ new ExtOpcode("RES 2, (HL)", this.res_2_phl),
                /* 0x97 */ new ExtOpcode("RES 2, A", this.res_2_a),
                /* 0x98 */ new ExtOpcode("RES 3, B", this.res_3_b),
                /* 0x99 */ new ExtOpcode("RES 3, C", this.res_3_c),
                /* 0x9A */ new ExtOpcode("RES 3, D", this.res_3_d),
                /* 0x9B */ new ExtOpcode("RES 3, E", this.res_3_e),
                /* 0x9C */ new ExtOpcode("RES 3, H", this.res_3_h),
                /* 0x9D */ new ExtOpcode("RES 3, L", this.res_3_l),
                /* 0x9E */ new ExtOpcode("RES 3, (HL)", this.res_3_phl),
                /* 0x9F */ new ExtOpcode("RES 3, A", this.res_3_a),

                /* 0xA0 */ new ExtOpcode("RES 4, B", this.res_4_b),
                /* 0xA1 */ new ExtOpcode("RES 4, C", this.res_4_c),
                /* 0xA2 */ new ExtOpcode("RES 4, D", this.res_4_d),
                /* 0xA3 */ new ExtOpcode("RES 4, E", this.res_4_e),
                /* 0xA4 */ new ExtOpcode("RES 4, H", this.res_4_h),
                /* 0xA5 */ new ExtOpcode("RES 4, L", this.res_4_l),
                /* 0xA6 */ new ExtOpcode("RES 4, (HL)", this.res_4_phl),
                /* 0xA7 */ new ExtOpcode("RES 4, A", this.res_4_a),
                /* 0xA8 */ new ExtOpcode("RES 5, B", this.res_5_b),
                /* 0xA9 */ new ExtOpcode("RES 5, C", this.res_5_c),
                /* 0xAA */ new ExtOpcode("RES 5, D", this.res_5_d),
                /* 0xAB */ new ExtOpcode("RES 5, E", this.res_5_e),
                /* 0xAC */ new ExtOpcode("RES 5, H", this.res_5_h),
                /* 0xAD */ new ExtOpcode("RES 5, L", this.res_5_l),
                /* 0xAE */ new ExtOpcode("RES 5, (HL)", this.res_5_phl),
                /* 0xAF */ new ExtOpcode("RES 5, A", this.res_5_a),

                /* 0xB0 */ new ExtOpcode("RES 6, B", this.res_6_b),
                /* 0xB1 */ new ExtOpcode("RES 6, C", this.res_6_c),
                /* 0xB2 */ new ExtOpcode("RES 6, D", this.res_6_d),
                /* 0xB3 */ new ExtOpcode("RES 6, E", this.res_6_e),
                /* 0xB4 */ new ExtOpcode("RES 6, H", this.res_6_h),
                /* 0xB5 */ new ExtOpcode("RES 6, L", this.res_6_l),
                /* 0xB6 */ new ExtOpcode("RES 6, (HL)", this.res_6_phl),
                /* 0xB7 */ new ExtOpcode("RES 6, A", this.res_6_a),
                /* 0xB8 */ new ExtOpcode("RES 7, B", this.res_7_b),
                /* 0xB9 */ new ExtOpcode("RES 7, C", this.res_7_c),
                /* 0xBA */ new ExtOpcode("RES 7, D", this.res_7_d),
                /* 0xBB */ new ExtOpcode("RES 7, E", this.res_7_e),
                /* 0xBC */ new ExtOpcode("RES 7, H", this.res_7_h),
                /* 0xBD */ new ExtOpcode("RES 7, L", this.res_7_l),
                /* 0xBE */ new ExtOpcode("RES 7, (HL)", this.res_7_phl),
                /* 0xBF */ new ExtOpcode("RES 7, A", this.res_7_a),

                /* 0xC0 */ new ExtOpcode("SET 0, B", this.set_0_b),
                /* 0xC1 */ new ExtOpcode("SET 0, C", this.set_0_c),
                /* 0xC2 */ new ExtOpcode("SET 0, D", this.set_0_d),
                /* 0xC3 */ new ExtOpcode("SET 0, E", this.set_0_e),
                /* 0xC4 */ new ExtOpcode("SET 0, H", this.set_0_h),
                /* 0xC5 */ new ExtOpcode("SET 0, L", this.set_0_l),
                /* 0xC6 */ new ExtOpcode("SET 0, (HL)", this.set_0_phl),
                /* 0xC7 */ new ExtOpcode("SET 0, A", this.set_0_a),
                /* 0xC8 */ new ExtOpcode("SET 1, B", this.set_1_b),
                /* 0xC9 */ new ExtOpcode("SET 1, C", this.set_1_c),
                /* 0xCA */ new ExtOpcode("SET 1, D", this.set_1_d),
                /* 0xCB */ new ExtOpcode("SET 1, E", this.set_1_e),
                /* 0xCC */ new ExtOpcode("SET 1, H", this.set_1_h),
                /* 0xCD */ new ExtOpcode("SET 1, L", this.set_1_l),
                /* 0xCE */ new ExtOpcode("SET 1, (HL)", this.set_1_phl),
                /* 0xCF */ new ExtOpcode("SET 1, A", this.set_1_a),

                /* 0xD0 */ new ExtOpcode("SET 2, B", this.set_2_b),
                /* 0xD1 */ new ExtOpcode("SET 2, C", this.set_2_c),
                /* 0xD2 */ new ExtOpcode("SET 2, D", this.set_2_d),
                /* 0xD3 */ new ExtOpcode("SET 2, E", this.set_2_e),
                /* 0xD4 */ new ExtOpcode("SET 2, H", this.set_2_h),
                /* 0xD5 */ new ExtOpcode("SET 2, L", this.set_2_l),
                /* 0xD6 */ new ExtOpcode("SET 2, (HL)", this.set_2_phl),
                /* 0xD7 */ new ExtOpcode("SET 2, A", this.set_2_a),
                /* 0xD8 */ new ExtOpcode("SET 3, B", this.set_3_b),
                /* 0xD9 */ new ExtOpcode("SET 3, C", this.set_3_c),
                /* 0xDA */ new ExtOpcode("SET 3, D", this.set_3_d),
                /* 0xDB */ new ExtOpcode("SET 3, E", this.set_3_e),
                /* 0xDC */ new ExtOpcode("SET 3, H", this.set_3_h),
                /* 0xDD */ new ExtOpcode("SET 3, L", this.set_3_l),
                /* 0xDE */ new ExtOpcode("SET 3, (HL)", this.set_3_phl),
                /* 0xDF */ new ExtOpcode("SET 3, A", this.set_3_a),

                /* 0xE0 */ new ExtOpcode("SET 4, B", this.set_4_b),
                /* 0xE1 */ new ExtOpcode("SET 4, C", this.set_4_c),
                /* 0xE2 */ new ExtOpcode("SET 4, D", this.set_4_d),
                /* 0xE3 */ new ExtOpcode("SET 4, E", this.set_4_e),
                /* 0xE4 */ new ExtOpcode("SET 4, H", this.set_4_h),
                /* 0xE5 */ new ExtOpcode("SET 4, L", this.set_4_l),
                /* 0xE6 */ new ExtOpcode("SET 4, (HL)", this.set_4_phl),
                /* 0xE7 */ new ExtOpcode("SET 4, A", this.set_4_a),
                /* 0xE8 */ new ExtOpcode("SET 5, B", this.set_5_b),
                /* 0xE9 */ new ExtOpcode("SET 5, C", this.set_5_c),
                /* 0xEA */ new ExtOpcode("SET 5, D", this.set_5_d),
                /* 0xEB */ new ExtOpcode("SET 5, E", this.set_5_e),
                /* 0xEC */ new ExtOpcode("SET 5, H", this.set_5_h),
                /* 0xED */ new ExtOpcode("SET 5, L", this.set_5_l),
                /* 0xEE */ new ExtOpcode("SET 5, (HL)", this.set_5_phl),
                /* 0xEF */ new ExtOpcode("SET 5, A", this.set_5_a),

                /* 0xF0 */ new ExtOpcode("SET 6, B", this.set_6_b),
                /* 0xF1 */ new ExtOpcode("SET 6, C", this.set_6_c),
                /* 0xF2 */ new ExtOpcode("SET 6, D", this.set_6_d),
                /* 0xF3 */ new ExtOpcode("SET 6, E", this.set_6_e),
                /* 0xF4 */ new ExtOpcode("SET 6, H", this.set_6_h),
                /* 0xF5 */ new ExtOpcode("SET 6, L", this.set_6_l),
                /* 0xF6 */ new ExtOpcode("SET 6, (HL)", this.set_6_phl),
                /* 0xF7 */ new ExtOpcode("SET 6, A", this.set_6_a),
                /* 0xF8 */ new ExtOpcode("SET 7, B", this.set_7_b),
                /* 0xF9 */ new ExtOpcode("SET 7, C", this.set_7_c),
                /* 0xFA */ new ExtOpcode("SET 7, D", this.set_7_d),
                /* 0xFB */ new ExtOpcode("SET 7, E", this.set_7_e),
                /* 0xFC */ new ExtOpcode("SET 7, H", this.set_7_h),
                /* 0xFD */ new ExtOpcode("SET 7, L", this.set_7_l),
                /* 0xFE */ new ExtOpcode("SET 7, (HL)", this.set_7_phl),
                /* 0xFF */ new ExtOpcode("SET 7, A", this.set_7_a),
            };

        private struct ExtOpcode
        {
            public readonly string Mnemonic;
            public readonly Func<int> Func;

            public ExtOpcode(string name, Func<int> func)
            {
                this.Mnemonic = name;
                this.Func = func;
            }
        }
    }
}